# Generated by Django 5.0.1 on 2024-01-09 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('seasonal', 'Seasonal'), ('single', 'Single')], max_length=10)),
                ('languages', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('malayalam', 'Malayalam'), ('tamil', 'Tamil'), ('kannada', 'Kannada'), ('telugu', 'Telugu'), ('bengali', 'Bengali')], max_length=20)),
                ('age_limit', models.CharField(choices=[('ALL', 'ALL'), ('Kids', 'Kids')], max_length=10)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy')], max_length=100)),
                ('length', models.PositiveIntegerField()),
                ('image_card', models.ImageField(upload_to='movie_images/')),
                ('image_cover', models.ImageField(upload_to='movie_images/')),
                ('video', models.FileField(upload_to='movie_videos/')),
                ('movie_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='media/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid_profiles', to='ottapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.movie')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=4)),
                ('avatar', models.ImageField(upload_to='media/')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ottapp.register')),
            ],
        ),
    ]
