# Generated by Django 5.0.1 on 2024-01-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0002_movie_register_expiry_date_register_joining_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Customer',
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=4)),
                ('avatar', models.ImageField(upload_to='media/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ottapp.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
