# Generated by Django 5.0.1 on 2024-01-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0003_rename_register_customer_customerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='for_kids',
            field=models.BooleanField(default=False),
        ),
    ]
